### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SpiritQuaddicted** [SpiritQuaddicted/quake-code-archives#8]
https://github.com/frabbani/quakec
https://github.com/frabbani/quakespasm
https://github.com/andrei-drexler/q321
https://github.com/andrei-drexler/vkQuake
https://github.com/andrei-drexler/andrei-drexler.github.io

**Comment by SpiritQuaddicted** [comment]
https://github.com/whipowill/quake-mod-frikbot4
https://github.com/whipowill/quake-dir

**Comment by 3453-315h** [comment]
hey there is there a log or actual list of all the content within the archive?

**Comment by SpiritQuaddicted** [comment]
https://github.com/viciious/tochris
https://github.com/viciious/noesis_iqe
